#include "shell.h"
#include "splash.h"
#include "vga.h"

#define SPLASH_WIDTH 120

static const unsigned char palette[] = { ':', 0xDB, ' ', '=', '-', '.' };
static const char splash_art[] =
    "AAAAAAAAAAAAAAAAAAAAAAAAAEZJMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZJLgAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEJMZAAAAZJJLgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "ADJjJcAABJJJJJJMAAAAAAAJYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEJgZAjbbJLSSSVZJJJJYAAAJIAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAABYABJJJJJSSSSSSJJJJJLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEgAAAADJJFSBNSSSSSpISSSB"
    "JMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEJJgAAAJJSTaSSSSSSSISSSgVpJgAAJJMAAAAAAAAAAAAAAAAAAAAAAAAAAABIBIA"
    "AEJaSSUiSSSSSSqSSSSRaJIABJJJAAAAAAAAAAAAAAAAAAAAAAAAAAAAJBYAABJSrSSSSSSSTCSSSSTriJIAJJJIAAAAAAAAAAAA"
    "AAAAAAAAAAAAAJLADJAAjJJqSSSSSSSSVriSSSSSSJIAJJYAAAAAAAAAAAAAAAAAAAAAAAAABIBIAAAZJJJLoASSSSSSSSSSSSSS"
    "TJLAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAJJJAAhJdSSZcjJCDJLiSSSSSSSSSrJIAAAAAAAAAAAAAAAAAAAAAAAAAAAhJMAEDJJI"
    "SSSCSSVJMEZJNSSStSSSSSpJAAAhJIAAAAAAAAAAAAAAAAAAAAAJEJYAJJkCSSSSSSStSSSpJttogFtFSSRJAABMAZAAAAAAAAAA"
    "AAAAAAAAAAAhJbgBJCSSSqSSSSSSSSSSJIAZJcEYAoJLAAZbZJAAAAAAAAAAAAAAAAAAAAAAAAABJFqVoFttFSSSSUoaJJJJZJJJ"
    "JJJIAAJLkAAAAAAAAAAAAAAAAAAAAADbYAABJIAAZMADIAtqSSSQJJZJJJlQZLJIAAAAAAAAAAAAAAAAAAAAAAAAABJJJLAAJJJJ"
    "LJJJJJIFSSSSUJJMtdSSSSBJAAAEgAAAAAAAAAAAAAAAAAAAAhcZLkAAJLZJJJJbbZJAAFSSSZIFSdUJaUJJkZJJJYAAAAAAAAAA"
    "AAAAAAAAADJLAAADJJIqSojJJJJJJIttoZMDdSRYJhJJJJLFZJgAAAAAAAAAAAAAAAAAAAAAAAABJAAqSSSSVDJJJJgAEJNJJCRY"
    "EJBJIqttVJLAAAAAAAAAAAAAAAAAAAEJJLgZLDJJdSSSSSSSEJJJJJhJZNRIAhJkAZJJiTJIAAAAAAAAAAAAAAAAAEJJJJJJJJJk"
    "ZcJdSSSSSSDJJJJbbJJgMBJJJJJJJShJAAAAAAAAAAAAAAAAAZJCSVDJJJLAAJAJSSVSSVAJIBLbJBIAAEIJJIAEJNUJIAAAAAAA"
    "AAAAAAAAEJKQZJctpJcAAIAhSBJJSVBJYBLbgAJEAAJZJJAAhJqJLAAAAAAAAAAAAAAAhJSZJJJJJJYABIABJLABaoJJgAJcAAZE"
    "AABhJJgAEJNRJAAAAAAAAAAAAAAEJKRJYAJJJJMAhAAAhgABiBJJgAhYAABIAADMJJIAAhJtJIAAAAAAAAAAAAABJSJMADJJZLAA"
    "JAAAJAAhghJJcABIAAAIAAAJJJLAABJgJMAAAAAAAAAAAAAJNTJYABJJJMAEMAAAMZgBJLJJLAALAAAJAAAZhJJAAAJMZJAAAAAA"
    "AAAAAADJahJAAZJJJcABIAABIJABZLJJLgAZAAAhgAMBMJJIAAJMhJAAAAAAAAAAAABJkJIAAJJJJYAhgAABgAAZBBJLJcABYAAB"
    "IAAALJJMAAJMhJAAAAAAAAAAAAhJkJgADJJJLgAJAAAJAAALJZJJJbYEIAAALBIAJhJJABJkJMAAAAAAAAAAAAJLhJAABJJJLgAM"
    "AAALAAEIMJJJZLbgJAAAZAAABZJJJJLhJIAAAAAAAAAAAAJMhJAAZJJJbYBIAABIAABZMJJZJLbbZYAABIAhMIJJJJjJJAAAAAAA"
    "AAAAAAZLjJAAJJLJbcBgAABYAAhBhJJJLJbbZLkAEMADgJZJLZJJgAAAAAAAAAAAAABJkJJkJJJLbbJAAAJADYJJhMZJJJbJbJbb"
    "kJAAAhhJJJJAAAAAAAAAAAAAAAEJLhJJJJZLbbLAAALAAEIMJIBJJZLJbJbbbZLkchLJJLAAAAAAAAAAAAAAAAAhJLkJJJJbbZLg"
    "ADIDgBMMJYEJJJJbbZLbbZLbLbJJhJIAAAAAAAAAAAAAAAAAZJJJJLJbbZLbABYBIhhZJAAJLJJZJZJbbbJbbJLoJJLAAAAAAAAA"
    "AAAAAAAAAjJJJJLbbJbbcJAAAJhhLAAhJJZLbbJbbbJJJlrLsJMAAAAAAAAAAAAAAAAAAAZJJZLZLJbbbJkAEMJJIAABJZJLbbZL"
    "JJJlSStBJJAAAAAAAAAAAAAAAAAAABJLJJLbZLbbZLbchMIJYAAAJJLJbJJJMCSSSrJJLAAAAAAAAAAAAAAAAAAAABJJJbJJJLbb"
    "ZLbbJJJJAAAAZJJJJJLgtttEJJJYAAAAAAAAAAAAAAAAAAAAABJJZJgthJJJJbbbJJJJADYAhJJckkkkkZJJJMAAAAAAAAAAAAAA"
    "AAAAAAAAAAhJJLkgqSVEZJJJJJJIAhLAhJJJcjZJJJJcAAAAAAAAAAAAAAAA";

static unsigned char waiting_for_key;

static unsigned char decode_symbol(char character)
{
    if (character >= 'A' && character <= 'Z') {
        return (unsigned char)(character - 'A');
    }
    if (character >= 'a' && character <= 'z') {
        return (unsigned char)(character - 'a' + 26);
    }
    if (character >= '0' && character <= '9') {
        return (unsigned char)(character - '0' + 52);
    }
    if (character == '-') {
        return 62;
    }

    return 63;
}

void splash_show(void)
{
    const char *encoded = splash_art;
    unsigned int column = 0;

    vga_clear();
    while (*encoded != '\0') {
        unsigned char value = decode_symbol(*encoded);
        unsigned int shift;

        encoded++;
        for (shift = 3;; shift -= 3) {
            vga_write_char((char)palette[(value >> shift) & 0x07U]);
            column++;
            if (column == SPLASH_WIDTH) {
                vga_write_char('\n');
                column = 0;
            }
            if (shift == 0) {
                break;
            }
        }
    }

    vga_write("Press any key to start BeerOS.");
    waiting_for_key = 1;
}

int splash_handle_key(void)
{
    if (waiting_for_key == 0) {
        return 0;
    }

    waiting_for_key = 0;
    vga_clear();
    shell_init();
    return 1;
}
